#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=200M
#SBATCH --time=2-05:00           # time (DD-HH:MM)
#SBATCH --account=rrg-jsirker-ab
module load python/2.7.13 
module load python27-scipy-stack/2017a
module load imkl/2017.1.132
cd /home/lcyc29/project/lcyc29/jobs/L800


srun python ./spssh.py -L 800 -W 1.0 -delta 0.3 -dt1 0.0008 -dt2 0.05 -tmid 2 -tmax 10 -dat 5 -sample 50 > /home/lcyc29/project/lcyc29/jobs/L800/D03W1dat01.dat

